# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        run: |
          docker build . -f docker/front/Dockerfile \
            -t ${{secrets.DOCKER_USER}}/website-static:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-static:latest
          docker build . -f docker/back/Dockerfile \
            -t ${{secrets.DOCKER_USER}}/website-api:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-api:latest
          docker push ${{secrets.DOCKER_USER}}/website-api:${{env.tag}}
          docker push ${{secrets.DOCKER_USER}}/website-api:latest
          docker push ${{secrets.DOCKER_USER}}/website-static:${{env.tag}}
          docker push ${{secrets.DOCKER_USER}}/website-static:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: shantysocial/msmtp
