# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Test & lint
        run: |
          sudo apt install -y python3-pip
          sudo pip3 install pipenv
          make ci

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        run: |
          docker build . -f docker/certbot/Dockerfile \
            --push \
            -t ${{secrets.DOCKER_USER}}/website-certbot:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-certbot:latest
          docker build . -f docker/website/Dockerfile \
            --push --target=final \
            -t ${{secrets.DOCKER_USER}}/website-final:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-final:latest
          docker build . -f docker/powerdns/Dockerfile \
            --push \
            -t ${{secrets.DOCKER_USER}}/website-dns:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-dns:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/website-api

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/website-static
