# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Test & lint
        run: |
          sudo apt install -y python3-pip
          sudo pip3 install pipenv
          make ci

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        run: |
          docker build . -f docker/website/Dockerfile \
            --target=static \
            -t ${{secrets.DOCKER_USER}}/website-static:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-static:latest
          docker build . -f docker/website/Dockerfile \
            --target=python \
            -t ${{secrets.DOCKER_USER}}/website-api:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-api:latest
          docker build . -f docker/website/Dockerfile \
            --target=beat \
            -t ${{secrets.DOCKER_USER}}/website-beat:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-beat:latest
          docker build . -f docker/website/Dockerfile \
            --target=celery \
            -t ${{secrets.DOCKER_USER}}/website-celery:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-celery:latest
          docker build . -f docker/website/Dockerfile \
            --target=migrate \
            -t ${{secrets.DOCKER_USER}}/website-migrate:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-migrate:latest
          docker build . -f docker/powerdns/Dockerfile \
            -t ${{secrets.DOCKER_USER}}/website-dns:${{env.tag}} \
            -t ${{secrets.DOCKER_USER}}/website-dns:latest
          docker push -a ${{secrets.DOCKER_USER}}/website-static
          docker push -a ${{secrets.DOCKER_USER}}/website-api
          docker push -a ${{secrets.DOCKER_USER}}/website-beat
          docker push -a ${{secrets.DOCKER_USER}}/website-celery
          docker push -a ${{secrets.DOCKER_USER}}/website-migrate
          docker push -a ${{secrets.DOCKER_USER}}/website-dns

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/website-api

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/website-static
